version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.14.0
    commands:
      - echo Installing dependencies...
      - npm --version
      - npm install --include=dev
      - npm list --depth=0
  build:
    commands:
      - echo Building the Vue.js app...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist
