// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint: 'https://zf3f65xkpjgynm44uzq4h7en5a.appsync-api.eu-north-1.amazonaws.com/graphql',
      region: 'eu-north-1',
      defaultAuthMode: 'apiKey',
      apiKey: 'da2-vuddwk7tbbgivowujj6su4jdqi'
    }
  }
};

export default config;
